# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages


bioc_required: true
bioc_use_devel: true

os:
 - linux
 - osx

r:
 - bioc-devel
 - oldrel
 - release
 - devel

r_github_packages:
 - Bioconductor-mirror/zlibbioc
 - Bioconductor-mirror/rhdf5
 - hadley/devtools#1263
 - rte-antares-rpackage/antares-rpackageRead@develop


include:
  - r: release
  - r: oldrel
  - r: devel

r_packages:
  - covr
  - devtools
  - data.table
  - lubridate
  - plyr
  - stringr
  - shiny
  - knitr


after_success:
  - Rscript -e 'library(covr); codecov()'
